//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CREDITOS_DOÑALOLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoPagos
    {
        public int Id { get; set; }
        public decimal Monto { get; set; }
        public int PeriodoPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public bool Estatus { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
